# ============================
# MODEL
# ============================
model:
  type: mae      # Options: 'mae', 'dino'

# ============================
# TRAINING
# ============================
training:
  batch_size_per_gpu: 64
  num_epochs: 100
  total_samples_per_epoch: 2000000

  print_every_steps: 500
  checkpoint_every_epochs: 10

  seed: 42

# ============================
# DATA
# ============================
data:
  data_root: "/cluster/work/lawecon_repo/gravestones/rep_learning_dataset/shards/"
  shards: "gravestones_shard_{000000..000999}.tar"
  num_workers: 4
  shuffle_buffer: 1000

# ============================
# LOGGING
# ============================
logging:
  log_root: "/cluster/home/jiapan/Supervised_Research/logs/"
  checkpoint_root: "/cluster/home/jiapan/Supervised_Research/checkpoints/"
