name: env_gravestones
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - icu=75.1
  - ld_impl_linux-64=2.45
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.12.12
  - readline=8.2
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - ansicolors==1.1.8
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - anysqlite==0.0.5
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.0.5
      - attrs==25.4.0
      - autoflake==2.3.1
      - babel==2.17.0
      - backrefs==6.1
      - bandit==1.8.6
      - beautifulsoup4==4.14.2
      - black==25.11.0
      - bleach==6.3.0
      - blinker==1.9.0
      - braceexpand==0.1.7
      - build==1.3.0
      - bump2version==1.0.1
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - colorful==0.5.8
      - comm==0.2.3
      - contourpy==1.3.3
      - coverage==7.11.3
      - cryptography==46.0.3
      - csscompressor==0.9.5
      - cycler==0.12.1
      - daal==2025.9.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dep-logic==0.5.2
      - diffusers==0.35.2
      - distlib==0.4.0
      - docutils==0.22.3
      - einops==0.8.1
      - entrypoints==0.4
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.0
      - findpython==0.7.1
      - flake8==7.3.0
      - fonttools==4.60.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - ghp-import==2.1.0
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - googleapis-common-protos==1.72.0
      - griffe==1.15.0
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - hishel==0.1.5
      - htmlmin2==0.1.13
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - icecream==2.1.8
      - id==1.5.0
      - identify==2.6.15
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - iniconfig==2.3.0
      - installer==0.7.0
      - iopath==0.1.10
      - ipykernel==6.31.0
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - isort==7.0.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.3.0
      - jedi==0.19.2
      - jeepney==0.9.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsmin==3.0.1
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.6.3
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - jupytext==1.18.1
      - keyring==25.7.0
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lightning-utilities==0.15.2
      - linformer==0.2.3
      - lmdb==1.7.5
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mccabe==0.7.0
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mergedeep==1.3.4
      - mistune==3.1.4
      - mkdocs==1.6.1
      - mkdocs-autorefs==1.4.3
      - mkdocs-get-deps==0.2.0
      - mkdocs-jupyter==0.25.1
      - mkdocs-material==9.7.0
      - mkdocs-material-extensions==1.3.1
      - mkdocs-minify-plugin==0.8.0
      - mkdocstrings==0.30.1
      - mkdocstrings-python==1.19.0
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - mypy==1.18.2
      - mypy-extensions==1.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - nh3==0.3.2
      - nodeenv==1.9.1
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==2.3.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opentelemetry-api==1.38.0
      - opentelemetry-exporter-prometheus==0.59b0
      - opentelemetry-proto==1.38.0
      - opentelemetry-sdk==1.38.0
      - opentelemetry-semantic-conventions==0.59b0
      - packaging==25.0
      - paginate==0.5.7
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - papermill==2.6.0
      - parso==0.8.5
      - pathspec==0.12.1
      - pbs-installer==2025.10.31
      - pdm==2.26.1
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - portalocker==3.2.0
      - pre-commit==4.4.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - psycopg==3.2.13
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-spy==0.4.1
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycodestyle==2.14.0
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydocstyle==6.3.0
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pymdown-extensions==10.17.1
      - pyparsing==3.2.5
      - pyproject-hooks==1.2.0
      - pytest==9.0.1
      - pytest-cov==7.0.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - pytokens==0.3.0
      - pytorch-lightning==2.5.6
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyyaml-env-tag==1.1
      - pyzmq==27.1.0
      - ray==2.51.1
      - readme-renderer==44.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - resolvelib==1.2.1
      - rfc3339-validator==0.1.4
      - rfc3986==2.0.0
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.29.0
      - rsa==4.9.1
      - ruff==0.14.5
      - safetensors==0.6.2
      - scienceplots==2.2.0
      - scikit-learn==1.7.2
      - scikit-learn-intelex==2025.9.0
      - scipy==1.16.3
      - seaborn==0.13.2
      - secretstorage==3.4.1
      - send2trash==1.8.3
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.5.0
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - socksio==1.0.0
      - soupsieve==2.8
      - stack-data==0.6.3
      - stevedore==5.5.0
      - submitit==1.5.3
      - sympy==1.14.0
      - tbb==2022.3.0
      - tcmlib==1.4.1
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.2.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenize-rt==6.2.0
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - torch==2.9.1
      - torchmetrics==1.8.2
      - torchvision==0.24.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.1
      - triton==3.5.1
      - truststore==0.10.4
      - twine==6.2.0
      - typer==0.20.0
      - types-pyyaml==6.0.12.20250915
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - unearth==0.18.1
      - uri-template==1.3.0
      - urllib3==2.5.0
      - virtualenv==20.35.4
      - vit-pytorch==1.15.7
      - watchdog==6.0.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webdataset==1.0.2
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - yarl==1.22.0
      - zipp==3.23.0
